@echo off
%~d0
cd %~dp0
@echo [E1000200h]
E1.EXE %1 /1 --
@echo.
rem @echo [E1000220h]
rem E1.EXE %1 /b /1 --
rem @echo.
rem @echo [E1000240h]
rem E1.EXE %1 /c /1 --
rem @echo.
rem @echo [E1000300h]
rem E1.EXE %1 /d /1 --
rem @echo.
rem @echo [E1000320h]
rem E1.EXE %1 /e /1 --
rem @echo.
rem @echo [E1000340h]
rem E1.EXE %1 /f /1 --
rem @echo.
rem @echo [E1000400h]
rem E1.EXE %1 /g /1 --
rem @echo.
rem @echo [E1000420h]
rem E1.EXE %1 /h /1 --
rem @echo.
rem @echo [E1000440h]
rem E1.EXE %1 /i /1 --
rem @echo.
rem @echo [E1000500h]
rem E1.EXE %1 /j /1 --
rem @echo.
rem @echo [E1000520h]
rem E1.EXE %1 /k /1 --
rem @echo.
rem @echo [E1000540h]
rem E1.EXE %1 /l /1 --
rem @echo.
rem @echo [E1000600h]
rem E1.EXE %1 /m /1 --
rem @echo.
rem @echo [E1000620h]
rem E1.EXE %1 /n /1 --
rem @echo.
rem @echo [E1000640h]
rem E1.EXE %1 /o /1 --
rem @echo.
rem @echo [E1000700h]
rem E1.EXE %1 /p /1 --
rem @echo.
rem @echo [E1000720h]
rem E1.EXE %1 /q /1 --
rem @echo.
rem @echo [E1000740h]
rem E1.EXE %1 /r /1 --
rem @echo.
rem @echo [ALL]
rem E1.EXE %1 /a /1 --
rem @echo.
@echo [OLDSCHOOL SHIT]
E1.EXE %1 /z /1 --
@echo.
@echo [R4MSC4N]
E1.EXE %1 /x /1
