@echo off
%~d0
cd %~dp0
rem @echo [E1000200h]
rem E1.EXE %1 --
rem @echo.
rem @echo [E1000220h]
rem E1.EXE %1 /b --
rem @echo.
rem @echo [E1000240h]
rem E1.EXE %1 /c --
rem @echo.
rem @echo [E1000300h]
rem E1.EXE %1 /d --
rem @echo.
rem @echo [E1000320h]
rem E1.EXE %1 /e --
rem @echo.
rem @echo [E1000340h]
rem E1.EXE %1 /f --
rem @echo.
rem @echo [E1000400h]
rem E1.EXE %1 /g --
rem @echo.
rem @echo [E1000420h]
rem E1.EXE %1 /h --
rem @echo.
rem @echo [E1000440h]
rem E1.EXE %1 /i --
rem @echo.
rem @echo [E1000500h]
rem E1.EXE %1 /j --
rem @echo.
rem @echo [E1000520h]
rem E1.EXE %1 /k --
rem @echo.
rem @echo [E1000540h]
rem E1.EXE %1 /l --
rem @echo.
rem @echo [E1000600h]
rem E1.EXE %1 /m --
rem @echo.
rem @echo [E1000620h]
rem E1.EXE %1 /n --
rem @echo.
rem @echo [E1000640h]
rem E1.EXE %1 /o --
rem @echo.
rem @echo [E1000700h]
rem E1.EXE %1 /p --
rem @echo.
rem @echo [E1000720h]
rem E1.EXE %1 /q --
rem @echo.
rem @echo [E1000740h]
rem E1.EXE %1 /r --
rem @echo.
rem @echo [ALL]>>CHEATS.TXT
E1.EXE %1 /a -->>CHEATS.TXT
rem @echo.
rem @echo [OLDSCHOOL SHIT]
rem E1.EXE %1 /z --
rem @echo.
rem @echo [R4MSC4N]
rem E1.EXE %1 /x
